### ISSUE TITLE
Possible to add custom colour highlighting on the settings?

### ISSUE THREAD

**Issue by KoichaDev** [lijyze/obsidian-advanced-codeblock#12]
![SCR-20230927-ehg](https://github.com/lijyze/obsidian-advanced-codeblock/assets/22475147/97df9b90-5793-4a7e-a469-f530ac7d1c92)

I find the color contrast when highlighting the code line is weak, and I need to make it look "stronger". It would be very nice to have such feature where I can add my own colour choice and opacity selection as well.

Anyhow, this is a very good plugin! Thanks for creating this! 🙂

**Comment by lijyze** [comment]
Thif feature means I have to modify css in javascript, which is I trying to avoid. So I'm not going to add such configeration.

But you have alternate way to reach that place.

You can add css snippets in `Settings/Appearance/CSS Snippets`, then add following code into it;
```css
.HyperMD-codeblock.live-preview-codeblock-highlight {
  background: /*COLOR YOU WANT*/;
}
.line-highlight {
  background: /*COLOR YOU WANT*/;
}
```
